class Config:
    SUPABASE_URL = 'https://leiurblladhjvaqonvqc.supabase.co'
    SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlaXVyYmxsYWRoanZhcW9udnFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDc4ODA0NjYsImV4cCI6MjAyMzQ1NjQ2Nn0.GLigWdUFVgUuEoXx5vmP1g4amHZdMLX0raf2PtaGdaI'
